x20_gazebo:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 1000  

    # FL Controllers ---------------------------------------
    FL_hipx_controller:
        type: robot_joint_controller/RobotJointController
        joint: FL_HipX_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    FL_hipy_controller:
        type: robot_joint_controller/RobotJointController
        joint: FL_HipY_joint
        pid: {p: 300.0, i: 0.0, d: 8.0}

    FL_knee_controller:
        type: robot_joint_controller/RobotJointController
        joint: FL_Knee_joint
        pid: {p: 300.0, i: 0.0, d: 8.0}

    # FR Controllers ---------------------------------------
    FR_hipx_controller:
        type: robot_joint_controller/RobotJointController
        joint: FR_HipX_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    FR_hipy_controller:
        type: robot_joint_controller/RobotJointController
        joint: FR_HipY_joint
        pid: {p: 300.0, i: 0.0, d: 8.0}

    FR_knee_controller:
        type: robot_joint_controller/RobotJointController
        joint: FR_Knee_joint
        pid: {p: 300.0, i: 0.0, d: 8.0}

    # HL Controllers ---------------------------------------
    HL_hipx_controller:
        type: robot_joint_controller/RobotJointController
        joint: HL_HipX_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    HL_hipy_controller:
        type: robot_joint_controller/RobotJointController
        joint: HL_HipY_joint
        pid: {p: 300.0, i: 0.0, d: 8.0}

    HL_knee_controller:
        type: robot_joint_controller/RobotJointController
        joint: HL_Knee_joint
        pid: {p: 300.0, i: 0.0, d: 8.0}

    # HR Controllers ---------------------------------------
    HR_hipx_controller:
        type: robot_joint_controller/RobotJointController
        joint: HR_HipX_joint
        pid: {p: 100.0, i: 0.0, d: 5.0}

    HR_hipy_controller:
        type: robot_joint_controller/RobotJointController
        joint: HR_HipY_joint
        pid: {p: 300.0, i: 0.0, d: 8.0}

    HR_knee_controller:
        type: robot_joint_controller/RobotJointController
        joint: HR_Knee_joint
        pid: {p: 300.0, i: 0.0, d: 8.0}

